### ISSUE TITLE
VG doesn't properly load paths that contain cycles. 

### ISSUE THREAD

**Issue by glennhickey** [ekg/vg#130] opened 2015-10-23 16:22 UTC
(discussed in #127, but worthy of its own issue)

When loading a graph from, say, json, paths get copied in with Paths::append_mapping().   This method uses Paths::has_mapping() to strip out any mapping its seen before.  The result is that paths with cycles are silently corrupted.

**Comment by ekg** [comment] 2015-10-27 11:11
There are a number of problems with path ordering in serialization. Looking into it now.

**Comment by ekg** [comment] 2015-10-27 14:54
Here's a graph with a cycle in a path. Things don't go very well for it.

```json
{"node":[{"sequence":"TCAGATTCTCATCCCTCCTCAAGGGCTTCT","id":1},{"sequence":"AACTACTCCACATCAAAGCTAC","id":2},{"sequence":"CCAGGCCATTTTAAGTTTCCTG","id":3},{"sequence":"T","id":4},{"sequence":"GGACTAAGGACAAAGGTGCGGGGAG","id":5}],"path":[{"mapping":[{"position":{"node_id":1},"edit":[{"from_length":15,"to_length":15}]},{"position":{"node_id":2},"edit":[{"from_length":5,"to_length":5}]},{"position":{"node_id":3},"edit":[{"from_length":3,"to_length":3}]},{"position":{"node_id":4},"edit":[{"from_length":1,"to_length":1}]},{"position":{"node_id":5},"edit":[{"from_length":10,"to_length":10}]}],"name":"s1"},{"mapping":[{"position":{"node_id":1},"edit":[{"from_length":15,"to_length":15}]},{"position":{"node_id":5},"edit":[{"from_length":5,"to_length":5}]},{"position":{"node_id":1},"edit":[{"from_length":15,"to_length":15}]},{"position":{"node_id":2},"edit":[{"from_length":5,"to_length":5}]},{"position":{"node_id":3},"edit":[{"from_length":3,"to_length":3}]},{"position":{"node_id":4},"edit":[{"from_length":1,"to_length":1}]},{"position":{"node_id":5},"edit":[{"from_length":10,"to_length":10}]}],"name":"s2"}],"edge":[{"from":1,"to":5},{"from":1,"to":2},{"from":2,"to":3},{"from":3,"to":4},{"from":4,"to":5},{"from":5,"to":1}]}
```

**Comment by ekg** [comment] 2015-10-27 16:53
Now, to generate a cyclic path via alignment.

**Comment by ekg** [comment] 2015-10-27 18:15
When we serialize the graph, it gets broken into chunks. Paths get crushed at this point because they're passed through a simplistic model I implemented early in vg's life when it only worked on DAGs. [We retain information in paths.hpp about the relative order of the mapping in the path, but this is not serialized along with the paths.](https://github.com/ekg/vg/blob/4ebfe853d7412a139753c3c3911a0f07c79bc86b/vg.cpp#L95-L113)

Paths with multiple crossings of a given node pose a problem here. What if our path loops through the region multiple times, but we can't see it "turning around" as it reverses outside of the subgraph. Then we won't know how to recombine the paths out of their components. The information is unavailable when we [restore the paths from a stream](https://github.com/ekg/vg/blob/4ebfe853d7412a139753c3c3911a0f07c79bc86b/vg.cpp#L1066) using [functionality in paths.cpp](https://github.com/ekg/vg/blob/4ebfe853d7412a139753c3c3911a0f07c79bc86b/path.cpp#L101-L109). The same problem is there when [we're reading from an arbitrary stream of protobuf objects](https://github.com/ekg/vg/blob/4ebfe853d7412a139753c3c3911a0f07c79bc86b/vg.cpp#L38-59), which is how the above test runs.

What we need to do is maintain the relationship between mapping and paths in a way that allows us to subset the paths but still understand how multiple mappings of a path across a node relate to the whole path. The simplest way I can think of is to record the path order within the path in each mapping in the serialized format. This will allow us to reconstruct the paths correctly no matter the order the chunks come in.

There are some additional things we might want to do, such as caching the total path length (in terms of nodes) in every reference to the path, but I don't think this is strictly necessary at first pass.

At least these need to happen:

1. Mappings must be extended to (optionally) retain their rank in their containing Path.
2. In `Path`, `map<int64_t, set<pair<string, Mapping*> > > node_mapping;` should be changed to `map<int64_t, map<string, set<Mapping*>>> node_mapping`

**Comment by ekg** [comment] 2015-10-28 10:29
Progress. I've added ranks to mappings and this seems to be working.

![screenshot from 2015-10-28 10 28 59](https://cloud.githubusercontent.com/assets/145425/10785875/bbcded34-7d5e-11e5-8315-ad539d665da7.png)

However, I had to manually generate the test case. I need to see if this can be done via alignment.

**Comment by JervenBolleman** [comment] 2015-10-28 10:46
@ekg is what you call ranks similar to what I called step in the RDF serialization?

**Comment by ekg** [comment] 2015-10-28 11:18
The rank is the position of the mapping in the larger path. This will allow the paths to be serialized in an non ordered way. I'm not sure this is what you're referring to in the RDF serialization. It adds a field to the protobuf for Mapping. I need to resolve some problems before pushing, see:

![screenshot from 2015-10-28 10 39 01](https://cloud.githubusercontent.com/assets/145425/10787005/a8775d40-7d65-11e5-9c9b-19b9cb624c02.png)

**Comment by JervenBolleman** [comment] 2015-10-28 11:24
@ekg,  then yes its the same. I had to make the implicit ordering in explicit for the RDF just as you are now doing for the JSON. Makes my life easier.

**Comment by ekg** [comment] 2015-10-28 11:32
@JervenBolleman sorry for the mistake on my end. I should have resolved this up-front.

**Comment by ekg** [comment] 2015-10-29 10:20
I've nearly finished resolving this. Something interesting came up and I'm trying to understand the cleanest representation.

When querying a larger graph we can end up with information about a subset of a path. In the current system the path is concatenated and there is an implication in some commands (vg view, vg validate) that the path is contiguous. However it isn't, and with the path ranks on the mappings we can check to see if the path is discontinuous and handle this sensibly.

These discontinuous paths could be used in a lot of ways. We could compress a graph mapping into one. There are two possible ways to do this sensibly.

1. Paths can be redefined as sets of contiguous mappings. This would necessitate a lot of code changes wherever paths are touched. The concept of rank would become confusing. Path = collection if mapping vectors seems like a confusing definition.

2. We can introduce a mapping value that serves as a sentinel for "end of subpath". This mapping would be empty but would have a rank. Its neighbors would then have discontinuous ranks.

I like the second way because we can use the ranks in graph validation. For included paths, mappings that have consecutive ranks should match to nodes that have edges between them. Otherwise we need not impose this constraint.

**Comment by ekg** [comment] 2015-10-29 12:46
Progress.

```
vg construct -r small/x.fa -v small/x.vcf.gz >x.vg
vg index -x t.xg -gd t.gcsa -k 11 t.vg
vg find -S AGGGCTTTTAACTACTCCACATCCAAAGCTACCCAGGCCATTTTAAGTTTCCTGT -z 7 x.vg | vg view -dpn - ...
```

![image](https://cloud.githubusercontent.com/assets/145425/10818625/02d20224-7e3b-11e5-9771-c8f64d36d1fb.png)

**Comment by ekg** [comment] 2015-10-29 12:47
In this example the point is that we can represent and visualize dispersed paths on the graph without considering the graph invalid or generating weird artifacts in the visualization.

**Comment by ekg** [comment] 2015-10-29 13:02
The GFA output has no mechanism for this. It will need to be extended to match the protobuf/RDF specs.

**Comment by ekg** [comment] 2015-10-29 14:46
Dispersed paths are working. Although, here their genesis is accidental.

![image](https://cloud.githubusercontent.com/assets/145425/10821747/d993e66e-7e4b-11e5-8657-b493d0ee5fe1.png)

**Comment by ekg** [comment] 2015-10-29 15:44
Now the problem is that xg doesn't handle the ranks. This isn't an issue for the rocksdb index, as it's storing the literal mapping objects.

**Comment by ekg** [comment] 2015-10-30 15:38
Gah, I need to test xg on some actual cyclic-path having graphs. Opening until I can re-resolve.

**Closed** 2015-10-30 16:18 UTC
Labels: in progress

**Comment by glennhickey** [comment] 2015-10-30 17:32
Cool, thanks for fixing this up so quickly!  I'll add support for "rank" to
our various converters today.

**Comment by ekg** [comment] 2015-10-30 18:04
Great :)

Now what generalization are we missing? I can't think of anything.

**Comment by adamnovak** [comment] 2015-10-30 21:28
It looks like `Paths::append_mapping(const string& name, const Mapping& m)` is still only adding mappings to paths that don't already contain a mapping to that node. Is that desirable? If not I can change it.

**Comment by ekg** [comment] 2015-10-30 22:21
No that's not correct, so change is welcome.

I haven't tested alignment generated cyclic paths. That probably would
uncover this.
